show databases;
CREATE DATABASE HIMS;
USE HIMS;

CREATE TABLE Country (
CountryID BIGINT AUTO_INCREMENT PRIMARY KEY,
CountryName VARCHAR(100) NOT NULL
);

CREATE TABLE State (
StateID BIGINT AUTO_INCREMENT PRIMARY KEY,
StateName VARCHAR(100) NOT NULL
);

CREATE TABLE City (
CityID BIGINT AUTO_INCREMENT PRIMARY KEY,
CityName VARCHAR(100) NOT NULL
);

CREATE TABLE Gender (
GenderID BIGINT AUTO_INCREMENT PRIMARY KEY,
GenderName VARCHAR(50) NOT NULL
);

CREATE TABLE BloodGroup (
BloodGroupID BIGINT AUTO_INCREMENT PRIMARY KEY,
BloodGroupName VARCHAR(10) NOT NULL
);

CREATE TABLE Department (
DepartmentID BIGINT AUTO_INCREMENT PRIMARY KEY,
DepartmentName VARCHAR(100) NOT NULL
);

CREATE TABLE Designation (
DesignationID BIGINT AUTO_INCREMENT PRIMARY KEY,
DesignationName VARCHAR(100) NOT NULL
);

CREATE TABLE Doctor (
DoctorID BIGINT AUTO_INCREMENT PRIMARY KEY,
DoctorName VARCHAR(100) NOT NULL,
GenderID BIGINT,
DepartmentID BIGINT,
DesignationID BIGINT,
ContactNumber VARCHAR(15),
Email VARCHAR(100),
Address VARCHAR(255),
Status BOOLEAN DEFAULT TRUE,
AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (GenderID) REFERENCES Gender(GenderID),
FOREIGN KEY (DepartmentID) REFERENCES Department(DepartmentID),
FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID)
);

CREATE TABLE Patient (
PatientID BIGINT AUTO_INCREMENT PRIMARY KEY,
PatientName VARCHAR(100) NOT NULL,
GenderID BIGINT,
BloodGroupID BIGINT,
DateOfBirth DATE,
ContactNumber VARCHAR(15),
Address VARCHAR(255),
CityID BIGINT,
StateID BIGINT,
CountryID BIGINT,
Status BOOLEAN DEFAULT TRUE,
AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (GenderID) REFERENCES Gender(GenderID),
FOREIGN KEY (BloodGroupID) REFERENCES BloodGroup(BloodGroupID),
FOREIGN KEY (CityID) REFERENCES City(CityID),
FOREIGN KEY (StateID) REFERENCES State(StateID),
FOREIGN KEY (CountryID) REFERENCES Country(CountryID)
);

CREATE TABLE Room (
RoomID BIGINT AUTO_INCREMENT PRIMARY KEY,
RoomNumber VARCHAR(10) NOT NULL,
RoomType VARCHAR(50),
ChargesPerDay DECIMAL(10,2),
Status BOOLEAN DEFAULT TRUE
);

CREATE TABLE Admission (
AdmissionID BIGINT AUTO_INCREMENT PRIMARY KEY,
PatientID BIGINT,
DoctorID BIGINT,
RoomID BIGINT,
AdmissionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
DischargeDate DATETIME,
Status BOOLEAN DEFAULT TRUE,
FOREIGN KEY (PatientID) REFERENCES Patient(PatientID),
FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID),
FOREIGN KEY (RoomID) REFERENCES Room(RoomID)
);

CREATE TABLE Visit (
VisitID BIGINT AUTO_INCREMENT PRIMARY KEY,
PatientID BIGINT,
DoctorID BIGINT,
VisitDate DATETIME DEFAULT CURRENT_TIMESTAMP,
Symptoms VARCHAR(255),
Diagnosis VARCHAR(255),
Status BOOLEAN DEFAULT TRUE,
FOREIGN KEY (PatientID) REFERENCES Patient(PatientID),
FOREIGN KEY (DoctorID) REFERENCES Doctor(DoctorID)
);

CREATE TABLE Prescription (
PrescriptionID BIGINT AUTO_INCREMENT PRIMARY KEY,
VisitID BIGINT,
MedicineName VARCHAR(255),
Dosage VARCHAR(100),
Duration VARCHAR(50),
FOREIGN KEY (VisitID) REFERENCES Visit(VisitID)
);

CREATE TABLE Bill (
BillID BIGINT AUTO_INCREMENT PRIMARY KEY,
AdmissionID BIGINT,
TotalAmount DECIMAL(10,2),
PaymentMode VARCHAR(50),
BillDate DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (AdmissionID) REFERENCES Admission(AdmissionID)
);

CREATE TABLE Staff (
StaffID BIGINT AUTO_INCREMENT PRIMARY KEY,
StaffName VARCHAR(100),
GenderID BIGINT,
DesignationID BIGINT,
ContactNumber VARCHAR(15),
Address VARCHAR(255),
Status BOOLEAN DEFAULT TRUE,
AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (GenderID) REFERENCES Gender(GenderID),
FOREIGN KEY (DesignationID) REFERENCES Designation(DesignationID)
);

CREATE TABLE `User` (
UserID BIGINT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(100) NOT NULL,
PasswordHash VARCHAR(255) NOT NULL,
Role VARCHAR(50),
StaffID BIGINT,
Status BOOLEAN DEFAULT TRUE,
AddedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (StaffID) REFERENCES Staff(StaffID)
);

CREATE TABLE Functionality (
FunctionalityID BIGINT AUTO_INCREMENT PRIMARY KEY,
FunctionalityName VARCHAR(100),
Description VARCHAR(255)
);

CREATE TABLE AccessRights (
AccessRightID BIGINT AUTO_INCREMENT PRIMARY KEY,
UserID BIGINT,
FunctionalityID BIGINT,
Status BOOLEAN DEFAULT TRUE,
FOREIGN KEY (UserID) REFERENCES `User`(UserID),
FOREIGN KEY (FunctionalityID) REFERENCES Functionality(FunctionalityID)
);

CREATE TABLE ClinicalNote (
ClinicalNoteID BIGINT AUTO_INCREMENT PRIMARY KEY,
AdmissionID BIGINT,
NoteDate DATETIME DEFAULT CURRENT_TIMESTAMP,
NoteText TEXT,
FOREIGN KEY (AdmissionID) REFERENCES Admission(AdmissionID)
);

CREATE TABLE Test (
TestID BIGINT AUTO_INCREMENT PRIMARY KEY,
TestName VARCHAR(100),
TestCharges DECIMAL(10,2)
);

CREATE TABLE PatientTest (
PatientTestID BIGINT AUTO_INCREMENT PRIMARY KEY,
AdmissionID BIGINT,
TestID BIGINT,
TestDate DATETIME DEFAULT CURRENT_TIMESTAMP,
Result VARCHAR(255),
FOREIGN KEY (AdmissionID) REFERENCES Admission(AdmissionID),
FOREIGN KEY (TestID) REFERENCES Test(TestID)
);

CREATE TABLE Medicine (
MedicineID BIGINT AUTO_INCREMENT PRIMARY KEY,
MedicineName VARCHAR(100),
Type VARCHAR(50),
Price DECIMAL(10,2)
);

CREATE TABLE PrescriptionMedicine (
PrescriptionMedicineID BIGINT AUTO_INCREMENT PRIMARY KEY,
PrescriptionID BIGINT,
MedicineID BIGINT,
Quantity INT,
FOREIGN KEY (PrescriptionID) REFERENCES Prescription(PrescriptionID),
FOREIGN KEY (MedicineID) REFERENCES Medicine(MedicineID)
);

CREATE TABLE Supplier (
SupplierID BIGINT AUTO_INCREMENT PRIMARY KEY,
SupplierName VARCHAR(100),
ContactNumber VARCHAR(15),
Address VARCHAR(255)
);

CREATE TABLE Inventory (
InventoryID BIGINT AUTO_INCREMENT PRIMARY KEY,
MedicineID BIGINT,
SupplierID BIGINT,
Quantity INT,
PurchaseDate DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (MedicineID) REFERENCES Medicine(MedicineID),
FOREIGN KEY (SupplierID) REFERENCES Supplier(SupplierID)
);




